# -*- coding: utf-8 -*-
"""SoC-25-OpenROAD-uart-demo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FuR-USrH-zey7Q06pWsDgBgTdMHWVaN6

# SoC-25 OpenROAD PU17 uart demo.

(C) DJ Greaves, University of Cambridge Computer Laboratory, Feb 2025.

This demo can be run on your own computer, or here in Google Colab.  

## Acknowledgements

- The set-up code is copied from [Chips Alliance's](https://github.com/chipsalliance/silicon-notebooks/blob/main/digital-inverter-openlane.ipynb) using the Apache 2.0 license.
"""



# Commented out IPython magic to ensure Python compatibility.
#
# SoC-25 OpenROAD PU17 uart demo
#
!date
import os
import pathlib

# Firstly - install the tools we need in the Colab VM.
#
# NB: The core of this set-up code was copied from the Chips Alliance Silicon Notebooks
# under the Apache 2.0 license.

!sudo apt-get update
!sudo apt-get install time

!curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xj bin/micromamba
conda_prefix_path = pathlib.Path('conda-env')
CONDA_PREFIX = str(conda_prefix_path.resolve())
!bin/micromamba create --yes --prefix $CONDA_PREFIX
!echo 'python ==3.7*' >> {CONDA_PREFIX}/conda-meta/pinned
!CI=0 bin/micromamba install --yes --prefix $CONDA_PREFIX \
                     --channel litex-hub \
                     --channel main \
                     openroad \
                     yosys \
                     klayout
#
!sudo pip install gdstk
#
!pip3 install pyyaml
PATH = os.environ['PATH']
# %env CONDA_PREFIX={CONDA_PREFIX}
# %env PATH={CONDA_PREFIX}/bin:{PATH}

!date
# Check tools are present and on the execution path.
!openroad -version
!yosys --version
!klayout -zz -v
# Fetch the workshop starter pack and unip it.
# Note, this refers to a temporary web page that worked for me. You can instead fetch
# it from the edX materials and then reupload it to Google Colab if you are using Colab.
!wget https://www.cl.cam.ac.uk/users/djg11/soc25-starter-packs/soc25-skills4-ws-starterpack-openroad.zip

# Unzip workshop starter pack
!unzip soc25-skills4-ws-starterpack-openroad.zip

# Get the OpenROAD flow scripts
!git clone https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts.git

# Before using Google Colab, I had run the OpenROAD yosys stage on my own workstation
# and then transfered my intermediate results to the cloud using the following zip.
# It is entirely up to you what balance between local and cloud mix you use.  The openROAD
# makefile should automatically join the gaps based on file time stamps.
!date; pwd
!cd results/nangate45; wget https://www.cl.cam.ac.uk/users/djg11/soc25-starter-packs/UART16-yosys-output.zip
!cd results/nangate45; unzip -o UART16-yosys-output.zip
!cd results/nangate45; touch UART16/base/* # Bring it up-to-date
!cd results/nangate45; ls -l UART16/base/

# Commented out IPython magic to ensure Python compatibility.
!date ; pwd
# Set the main environment variables
# %env YOSYS_EXE=yosys
# %env OPENROAD_EXE=openroad
# %env KLAYOUT_EXE=klayout
# Set the design-specific environment variables
# %env SOC25_STARTPACK=/content/soc25-skills4-ws-starterpack-openroad
# %env DESIGN_HOME=$(SOC25_STARTPACK)/uart16-demo
# %env DESIGN_CONFIG=$(DESIGN_HOME)/config-soc25-uart-openroad-demo.mk
# %env PLATFORM=nangate45
# %env DESIGN_NAME=UART16

# Needed to install again for some reason?
# !pip3 install pyyaml

# And finally launch the OpenROAD flow Makefile.
# %env SYNTH_OPERATIONS_ARGS=""
# %cd /content/OpenROAD-flow-scripts/flow
!make do-floorplan do-place do-cts do-route do-finish
!echo Done OpenROAD Makefile for SoC-25

# Now that we have a GDS-II layout file, lets download it to our workstation or PC
# for interactive examination. So zip up all the output results for download.
!pwd
!cd ..; zip -r dump-for-download-soc25-OR-uart-demo.zip flow/results flow/UART16 flow/scripts flow/Makefile

!date
import pathlib
import gdstk
import IPython.display

def gen_svg(): # This display code also based on Chips Alliance version, but not being used today anyway.
    gdss = sorted(pathlib.Path('.').glob('./results/nangate45/UART16/base/*.gds'))
    library = gdstk.read_gds(gdss[-1])
    top_cells = library.top_level()

    # this is to hide all layer labels
    label_style = {(i,0):  {"fill": "none", "stroke": "red", "font-size": "0px"} for i in range(256)}
    top_cells[0].write_svg('UART16.svg',
                       label_style=label_style)
    IPython.display.SVG('UART16.svg')

print(f'DJG end of flow')